













Quick Credit is an online lending platform that provides 
short term soft loans to individuals. This helps solve problems
 of financial inclusion as a way to alleviate poverty and empower 
low income earners.  throught this api documentation, users can be able to create loan account,
 to login, to request a loan as well as to view their tranctions history. 
the admin is the granted all privileges to make any request, to grant loans , 
to approve a loan application or to reject it, to see all loan history and manage each one, 
he can see also the specific loan corresponding 
to the user and finally he can post loan in favour of clients.